import { X, Download } from "lucide-react";

interface Props {
  letter: string;
  patientId: string;
  isDark: boolean;
  onClose: () => void;
}

export default function FamilyLetterView({ letter, patientId, isDark, onClose }: Props) {
  const handleDownload = () => {
    const blob = new Blob([letter], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `family-letter-${patientId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const bg = isDark ? "bg-dark-bg" : "bg-gray-50";
  const surface = isDark ? "bg-dark-surface border-dark-card" : "bg-white border-gray-200";
  const textP = isDark ? "text-txt-primary" : "text-gray-900";
  const textM = isDark ? "text-txt-muted" : "text-gray-500";

  return (
    <div className={`fixed inset-0 z-50 flex flex-col ${bg}`}>
      {/* Header */}
      <div className={`flex items-center justify-between px-10 py-5 border-b ${surface}`}>
        <div>
          <h1 className={`text-base font-semibold ${textP}`}>Family Communication Letter</h1>
          <p className={`text-xs mt-0.5 ${textM}`}>
            Patient {patientId} — generated by AI clinical assistant
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={handleDownload}
            className="flex items-center gap-2 h-9 px-4 bg-brand-blue text-white text-sm font-semibold hover:bg-blue-500 transition-colors"
          >
            <Download size={14} />
            Download
          </button>
          <button
            type="button"
            onClick={onClose}
            className={`flex items-center justify-center w-9 h-9 border hover:opacity-70 transition-opacity ${surface}`}
          >
            <X size={16} className={textP} />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto flex justify-center px-6 py-10">
        <div className={`max-w-2xl w-full border p-10 ${surface}`}>
          <p className={`text-sm leading-loose whitespace-pre-wrap ${textP}`}>{letter}</p>
        </div>
      </div>
    </div>
  );
}
